version: 2
jobs:
  setup:
    working_directory: ~/mock
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: [.]

  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - attach_workspace: { at: . }
      - run: yarn run tsc

  snyk:
    docker:
      - image: circleci/node:10.15
    steps:
      - attach_workspace: { at: . }
      - run:
          name: Snyk Setup
          command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh

  lint:
    docker:
      - image: circleci/node:10.15
    steps:
      - attach_workspace: { at: . }
      - run: yarn lint

workflows:
  version: 2
  default:
    jobs:
      - setup
      - build:
          requires: [setup]
      - snyk:
          context: snyk
          requires: [setup]
      - lint:
          requires: [setup]
